version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://emailapp:emailapp123@db:5432/emaildb
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=emailapp
      - POSTGRES_PASSWORD=emailapp123
      - POSTGRES_DB=emaildb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 